from erpnext.crm.doctype.lead.lead import Lead

class CustomLead(Lead):
    def set_status(self, update=False):
        # DO NOTHING → disable ERPNext logic
        pass
    # def set_status(self, update=False):
    #     return super().set_status(update=update)


import frappe

def create_lead_chat(doc, method=None):
    if isinstance(doc, str):
        doc = frappe.get_doc("Lead", doc)

    if frappe.db.exists("Lead Chat", {"lead": doc.name}):
        return

    user = doc.owner or frappe.session.user
    user_name = frappe.db.get_value("User", user, "full_name") or user
    try:
        lead_chat = frappe.new_doc("Lead Chat")
        lead_chat.lead = doc.name
        lead_chat.append("chat_history", {
            "message": f"This Lead generated by {user_name}",
            "user": user,
            "date": frappe.utils.now_datetime(),
        })
        lead_chat.insert(ignore_permissions=True)
    except Exception:
        frappe.log_error(frappe.get_traceback(), f"Lead Chat creation failed for {doc.name}")
        raise

def delete_lead_chat(doc, method=None):
    if isinstance(doc, str):
        doc = frappe.get_doc("Lead", doc)

    try:
        for lead_chat in frappe.get_all("Lead Chat", filters={"lead": doc.name}, pluck="name"):
            frappe.delete_doc("Lead Chat", lead_chat, ignore_permissions=True, force=True)
    except Exception:
        frappe.log_error(frappe.get_traceback(), f"Lead Chat deletion failed for {doc.name}")
        raise

@frappe.whitelist()
def add_lead_chat_message(lead, message):
    if not lead:
        frappe.throw("Lead is required")

    message = (message or "").strip()
    if not message:
        frappe.throw("Message is required")

    if not frappe.has_permission("Lead", "read", lead):
        frappe.throw("Not permitted", frappe.PermissionError)

    lead_chat_name = frappe.db.get_value("Lead Chat", {"lead": lead}, "name")
    if lead_chat_name:
        lead_chat = frappe.get_doc("Lead Chat", lead_chat_name)
    else:
        lead_chat = frappe.new_doc("Lead Chat")
        lead_chat.lead = lead

    lead_chat.append("chat_history", {
        "message": message,
        "user": frappe.session.user,
        "date": frappe.utils.now_datetime(),
    })
    lead_chat.save(ignore_permissions=True)

    return lead_chat.name


@frappe.whitelist()
def set_firm_name(firm_name):
    frim_name = frappe.get_value("Firm Name SPC", firm_name, ["architecture", "contractor", "applicator", "consultant"], as_dict=True)
    if frim_name.architecture == 1:
        custom_architecture == custom_firm_name_lead 

    
@frappe.whitelist()
def set_title_field(doc,method=None):
    doc.title = doc.custom_firm_name_lead

