from erpnext.crm.doctype.lead.lead import Lead

class CustomLead(Lead):
    def set_status(self, update=False):
        # DO NOTHING → disable ERPNext logic
        pass
    # def set_status(self, update=False):
    #     return super().set_status(update=update)


import json

import frappe
from frappe.desk.form import assign_to

def create_lead_chat(doc, method=None):
    if isinstance(doc, str):
        doc = frappe.get_doc("Lead", doc)

    if frappe.db.exists("Lead Chat", {"lead": doc.name}):
        return

    user = doc.owner or frappe.session.user
    user_name = frappe.db.get_value("User", user, "full_name") or user
    try:
        lead_chat = frappe.new_doc("Lead Chat")
        lead_chat.lead = doc.name
        lead_chat.append("chat_history", {
            "message": f"This Lead generated by {user_name}",
            "user": user,
            "date": frappe.utils.now_datetime(),
        })
        lead_chat.insert(ignore_permissions=True)
    except Exception:
        frappe.log_error(frappe.get_traceback(), f"Lead Chat creation failed for {doc.name}")
        raise

def delete_lead_chat(doc, method=None):
    if isinstance(doc, str):
        doc = frappe.get_doc("Lead", doc)

    try:
        for lead_chat in frappe.get_all("Lead Chat", filters={"lead": doc.name}, pluck="name"):
            frappe.delete_doc("Lead Chat", lead_chat, ignore_permissions=True, force=True)
    except Exception:
        frappe.log_error(frappe.get_traceback(), f"Lead Chat deletion failed for {doc.name}")
        raise

@frappe.whitelist()
def search_mention_users(txt=""):
    txt = (txt or "").strip()
    filters = {"enabled": 1, "user_type": "System User"}
    or_filters = None

    if txt:
        or_filters = {
            "name": ["like", f"%{txt}%"],
            "full_name": ["like", f"%{txt}%"],
        }

    return frappe.get_all(
        "User",
        fields=["name", "full_name"],
        filters=filters,
        or_filters=or_filters,
        order_by="full_name asc",
        limit_page_length=10,
    )


def _coerce_mentioned_users(mentioned_users):
    if not mentioned_users:
        return []

    if isinstance(mentioned_users, str):
        try:
            mentioned_users = json.loads(mentioned_users)
        except Exception:
            mentioned_users = [mentioned_users]

    if not isinstance(mentioned_users, (list, tuple, set)):
        return []

    clean_users = []
    for user in mentioned_users:
        user = (user or "").strip()
        if user and frappe.db.exists("User", {"name": user, "enabled": 1}):
            clean_users.append(user)

    return list(dict.fromkeys(clean_users))


def _assign_mentioned_users(lead, mentioned_users):
    for user in _coerce_mentioned_users(mentioned_users):
        assign_to.add({
            "assign_to": [user],
            "doctype": "Lead",
            "name": lead,
            "description": f"Mentioned in Lead chat by {frappe.session.user}",
        })


def _latest_submitted_quotation_for_lead(lead):
    return frappe.db.get_value(
        "Quotation",
        {"quotation_to": "Lead", "party_name": lead, "docstatus": 1},
        "name",
        order_by="modified desc",
    )


def _existing_customer_for_lead(lead):
    return frappe.db.get_value("Customer", {"lead_name": lead}, "name")


def _copy_child_rows(source_rows, fields):
    rows = []
    for source in source_rows or []:
        row = {field: source.get(field) for field in fields if source.get(field) is not None}
        if row:
            rows.append(row)
    return rows


@frappe.whitelist()
def get_sales_order_from_lead(lead):
    if not lead:
        frappe.throw("Lead is required")

    if not frappe.has_permission("Lead", "read", lead):
        frappe.throw("Not permitted", frappe.PermissionError)

    lead_doc = frappe.get_doc("Lead", lead)
    quotation_name = _latest_submitted_quotation_for_lead(lead)
    sales_order = frappe.new_doc("Sales Order")
    sales_order.order_type = "Sales"

    existing_customer = lead_doc.get("customer") or _existing_customer_for_lead(lead)
    if existing_customer:
        sales_order.customer = existing_customer
        sales_order.customer_name = frappe.db.get_value("Customer", existing_customer, "customer_name")
    else:
        sales_order.customer_name = lead_doc.get("lead_name") or lead_doc.get("company_name")

    if quotation_name:
        quotation = frappe.get_doc("Quotation", quotation_name)
        header_fields = [
            "company", "transaction_date", "valid_till", "order_type", "currency",
            "conversion_rate", "selling_price_list", "price_list_currency",
            "plc_conversion_rate", "ignore_pricing_rule", "taxes_and_charges",
            "tax_category", "customer_address", "shipping_address_name", "contact_person",
            "contact_display", "contact_email", "contact_mobile", "payment_terms_template",
            "tc_name", "terms", "letter_head", "campaign", "source", "territory",
            "customer_group", "cost_center", "company_address",
        ]
        for field in header_fields:
            if quotation.get(field) is not None:
                sales_order.set(field, quotation.get(field))

        if not sales_order.customer:
            sales_order.customer_name = quotation.get("customer_name") or sales_order.customer_name

        item_fields = [
            "item_code", "customer_item_code", "delivery_date", "item_name", "description",
            "gst_hsn_code", "item_group", "brand", "image", "qty", "stock_uom", "uom",
            "conversion_factor", "price_list_rate", "discount_percentage", "discount_amount",
            "rate", "amount", "item_tax_template", "gst_treatment", "base_rate",
            "base_amount", "net_rate", "net_amount", "base_net_rate", "base_net_amount",
            "warehouse", "against_blanket_order", "blanket_order", "blanket_order_rate",
            "bom_no", "cost_center", "project",
        ]
        for row in _copy_child_rows(quotation.items, item_fields):
            sales_order.append("items", row)

        tax_fields = [
            "charge_type", "row_id", "account_head", "description", "included_in_print_rate",
            "included_in_paid_amount", "cost_center", "rate", "account_currency",
            "tax_amount", "total", "tax_amount_after_discount_amount", "base_tax_amount",
            "base_total", "base_tax_amount_after_discount_amount", "item_wise_tax_detail",
            "dont_recompute_tax",
        ]
        for row in _copy_child_rows(quotation.taxes, tax_fields):
            sales_order.append("taxes", row)

        sales_team_fields = ["sales_person", "allocated_percentage", "commission_rate", "allocated_amount", "incentives"]
        for row in _copy_child_rows(quotation.get("sales_team"), sales_team_fields):
            sales_order.append("sales_team", row)

        sales_order.set("quotation", quotation.name) if sales_order.meta.has_field("quotation") else None

    sales_order.flags.ignore_permissions = True
    sales_order.run_method("set_missing_values")
    sales_order.run_method("calculate_taxes_and_totals")

    return {"sales_order": sales_order.as_dict(), "quotation": quotation_name}


def _get_user_from_email(email):
    email = (email or "").strip()
    if not email:
        return None

    return frappe.db.get_value(
        "User",
        {"email": email, "enabled": 1},
        "name",
    ) or frappe.db.get_value(
        "User",
        {"name": email, "enabled": 1},
        "name",
    )


def _get_receiver_users(doc):
    users = []
    for row in doc.get("custom_receiver_user_id") or []:
        user = (row.get("user") or "").strip()
        if user and frappe.db.exists("User", {"name": user, "enabled": 1}):
            users.append(user)

    return list(dict.fromkeys(users))


@frappe.whitelist()
def send_create_sales_order_notification(lead):
    if not lead:
        frappe.throw("Lead is required")

    if not frappe.has_permission("Lead", "write", lead):
        frappe.throw("Not permitted", frappe.PermissionError)

    doc = frappe.get_doc("Lead", lead)
    receivers = _get_receiver_users(doc)
    if not receivers:
        frappe.throw("Please select at least one enabled Receiver User.")

    if doc.custom_is_generate_sales_order:
        return {"status": "already_sent"}

    subject = "Create New Sales Order"
    content = f"Create New Sales Order request for Lead ID: {doc.name}"

    for receiver in receivers:
        frappe.get_doc({
            "doctype": "Notification Log",
            "subject": subject,
            "email_content": content,
            "for_user": receiver,
            "type": "Alert",
            "document_type": "Lead",
            "document_name": doc.name,
            "from_user": frappe.session.user,
        }).insert(ignore_permissions=True)

    doc.db_set("custom_is_generate_sales_order", 1, update_modified=True)
    frappe.db.commit()

    return {"status": "sent", "receivers": receivers}


@frappe.whitelist()
def add_lead_chat_message(lead, message, mentioned_users=None):
    if not lead:
        frappe.throw("Lead is required")

    message = (message or "").strip()
    if not message:
        frappe.throw("Message is required")

    if not frappe.has_permission("Lead", "read", lead):
        frappe.throw("Not permitted", frappe.PermissionError)

    lead_chat_name = frappe.db.get_value("Lead Chat", {"lead": lead}, "name")
    if lead_chat_name:
        lead_chat = frappe.get_doc("Lead Chat", lead_chat_name)
    else:
        lead_chat = frappe.new_doc("Lead Chat")
        lead_chat.lead = lead

    lead_chat.append("chat_history", {
        "message": message,
        "user": frappe.session.user,
        "date": frappe.utils.now_datetime(),
    })
    lead_chat.save(ignore_permissions=True)
    _assign_mentioned_users(lead, mentioned_users)

    return lead_chat.name


@frappe.whitelist()
def set_firm_name(firm_name):
    frim_name = frappe.get_value("Firm Name SPC", firm_name, ["architecture", "contractor", "applicator", "consultant"], as_dict=True)
    if frim_name.architecture == 1:
        custom_architecture == custom_firm_name_lead 

    
@frappe.whitelist()
def set_title_field(doc,method=None):
    doc.title = doc.custom_firm_name_lead




#*************************************************************************************************************************
def update_project_lead_todo(doc, method=None):
    sales_person = doc.custom_handover_to_project_lead

    if not sales_person:
        return

    # Only when Sales Person changes
    if not doc.is_new() and not doc.has_value_changed("custom_handover_to_project_lead"):
        return

    # Delete old ToDo
    frappe.db.delete("ToDo", {
        "reference_type": "Lead",
        "reference_name": doc.name
    })

    # Get Employee from Sales Person
    employee = frappe.db.get_value(
        "Sales Person",
        sales_person,
        "employee"
    )

    if not employee:
        frappe.throw(
            f"Please map an Employee for Sales Person: {sales_person}"
        )

    # Get User ID from Employee
    user = frappe.db.get_value(
        "Employee",
        employee,
        "user_id"
    )

    if not user:
        return

    frappe.share.add_docshare(
        "Lead",
        doc.name,
        user=user,
        read=1,
        write=1,
        flags={"ignore_share_permission": True},
    )

    # Create new ToDo
    frappe.get_doc({
        "doctype": "ToDo",
        "allocated_to": user,
        "reference_type": "Lead",
        "reference_name": doc.name,
        "description":  doc.name,
        "assigned_by": frappe.session.user
    }).insert(ignore_permissions=True)